### ISSUE TITLE
can use defaultdict in namecount.py

### ISSUE THREAD

**Issue by ryanfox** [iluxonchik/iluxonchik.github.com#1]
"Why you should learn Python" - nice read!  I noticed you can use a defaultdict in `namecount.py`:

```
names = {}
[...]
    if name in names:
        names[name] += 1
    else:
        names[name] = 1
```

This can be simplified to

```
from collections import defaultdict
[...]
names = defaultdict(int)
[...]
    names[name] += 1
```

So this would be the full `namecount.py`:

```
#!/usr/bin/env python3
import sys
from collections import defaultdict

def count_names():
    names = defaultdict(int)
    for name in sys.stdin.readlines():
        name = name.strip()
        names[name] += 1  # or combine this and the previous line

    for name, count in names.items():
        sys.stdout.write("{0}\t{1}\n".format(name, count))

if __name__ == "__main__":
    count_names()
```

Kind of a minor thing, but since the article is about the virtues of Python, I thought it'd be a nice addition.
(I'd fork and make a pull request, but looks like the repo has raw HTML rather than markdown or some such)

**Comment by iluxonchik** [comment]
Hey, thank you for your feedback and suggestion :smile:

> "Why you should learn Python" - nice read! I noticed you can use a defaultdict in

Someone has already pointed out that optimization and I actually included a `defaultdict` version at the end of the post (the **EDIT** section). Here's what it says:
- As per [jyf1987's suggestion](https://twitter.com/jyf1987/status/767906122200080384),
  here is a `namescount.py` version using `collections.defaultdict`: [namescount.py using defaultdict](https://gist.github.com/iluxonchik/348838b3547abf09587d5b4bcbb56f26).
  I'm keeping the original one in the post, because the goal was to be more explicit, so that people new to Python would have less trouble understanding it.

> (I'd fork and make a pull request, but looks like the repo has raw HTML rather than markdown or some such)

Oh yes, I'm using [Jekyll](https://jekyllrb.com/). Basically you write your posts in Markdown (with some extensions, like syntax highlighters), then use `Jekyll` to compile it to HTML.
So I basically have 2 branches: `source`, where the Jekyll source resides and `master`, where I put the generated HTML.

**Comment by ryanfox** [comment]
Cool.  Missed the edit I guess.

> So I basically have 2 branches: source, where the Jekyll source resides and master, where I put the generated HTML.

Different branch!  I figured it was Jekyll (does github pages support other site generators?), just couldn't find the source.

**Comment by iluxonchik** [comment]
> Different branch! I figured it was Jekyll (does github pages support other site generators?), just couldn't find the source.

I'm pretty sure you can use pretty much what you want, as long as it's HTML/JS/CSS.

**Comment by iluxonchik** [comment]
Maybe I wasn't super clear, but GitHub doesn't generate the HTML, you have to do it manually (or use something like [Travis CI](https://travis-ci.org/) integration to automate it)
